// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CenterContentSection: typeof import('./src/components/utilities/CenterContentSection.vue')['default']
    HeaderTwo: typeof import('./src/components/utilities/HeaderTwo.vue')['default']
    LegendPermissionStatus: typeof import('./src/components/LegendPermissionStatus.vue')['default']
    LoadingCircle: typeof import('./src/components/LoadingCircle.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    PermissionIconWrapper: typeof import('./src/components/utilities/PermissionIconWrapper.vue')['default']
    PermissionStatus: typeof import('./src/components/PermissionStatus.vue')['default']
    PermissionStatusIcon: typeof import('./src/components/utilities/PermissionStatusIcon.vue')['default']
    PermissionStatusLegendRow: typeof import('./src/components/PermissionStatusLegendRow.vue')['default']
  }
}
