// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    LoadingCircle: typeof import("./src/components/LoadingCircle.vue")["default"];
    LoginForm: typeof import("./src/components/LoginForm.vue")["default"];
    PermissionStatus: typeof import("./src/components/PermissionStatus.vue")["default"];
    TestAutoImport: typeof import("./src/components/TestAutoImport.vue")["default"];
  }
}
